### ISSUE TITLE
Agregar pequeña animación al actualizar pantalla de resultados

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#10]
Cuando el votante aprieta "Actualizar" en la pantalla de resultados, sería bueno que tuviera una pequeña animación que le informe al votante de que se fue a buscar información. Si no hay información, la pantalla queda igual. Si hubiera, se muestran los resultados.
La animación puede ser un modal

**Comment by JaramilloCris** [comment]
La consulta al ser tan rapida, creo que es mejor poner el spinner en vez de un modal (quedaría extraño con modal)
