### ISSUE TITLE
Ocultar la clave privada en la vista de custodios

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#124]
# Issue

Al generar desencriptación parcial se muestra la clave privada, esta no debe ser visible facilmente.

El objetivo es que si el custodio nos comparte pantalla, nosotros no podamos ver su clave privada, más allá de la existencia del archivo.

**Comment by fermacias** [comment]
![Image](https://github.com/clcert/psifos-frontend/assets/53621395/3ad80d58-1b3f-4f04-af1c-e5caeff3d24a)

**Comment by fermacias** [comment]
@camilog cuál es la prioridad de esto?

**Comment by camilog** [comment]
@fermacias Yo creo que es alta. Me gustaría que igual se muestre algo. Mejor mostremos un SHA3_512 de la clave.

**Comment by camilog** [comment]
Vamos a cerrar el issue, ya que lo actual (no mostrar nada) es lo mejor en este caso.
