### ISSUE TITLE
Mejorar dropdown en elecciones con mixnet

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#19]
Es necesario hacer dos cosas:

- [ ] Hacer más énfasis a que se puede buscar en el mismo dropdown. Para ello sería bueno cambiar el mensaje del placeholder para poder explicitar la posibilidad de buscar.
- [ ] Es necesario poder separar las candidaturas oficiales de las no oficiales. Una buena idea sería utilizar la propiedad GroupHeading del componente utilizado

**Comment by camilog** [comment]
Me gusta la idea de que esté en el padrón mismo el grupo al cual pertenece una persona.
Además, el nombre que aparece en el padrón debe ser el nombre del grupo que aparece en la misma interfaz. Quedaría algo así:
```
camilo,Camilo Gómez,1,Candidaturas Oficiales
ahevia,Alejandro Hevia,1,Candidaturas Oficiales
fmacias,Fernanda Macías,1,Otras Candidaturas
rdelafuente,Raul de la Fuente,1,Otras Candidaturas
```

**Comment by camilog** [comment]
Me gusta la idea de que esté en el padrón mismo el grupo al cual pertenece una persona.
Además, el nombre que aparece en el padrón debe ser el nombre del grupo que aparece en la misma interfaz. Quedaría algo así:
```
camilo,Camilo Gómez,1,Candidaturas Oficiales
ahevia,Alejandro Hevia,1,Candidaturas Oficiales
fmacias,Fernanda Macías,1,Otras Candidaturas
rdelafuente,Raul de la Fuente,1,Otras Candidaturas
```

**Comment by camilog** [comment]
Me gusta la idea de que esté en el padrón mismo el grupo al cual pertenece una persona.
Además, el nombre que aparece en el padrón debe ser el nombre del grupo que aparece en la misma interfaz. Quedaría algo así:
```
camilo,Camilo Gómez,1,Candidaturas Oficiales
ahevia,Alejandro Hevia,1,Candidaturas Oficiales
fmacias,Fernanda Macías,1,Otras Candidaturas
rdelafuente,Raul de la Fuente,1,Otras Candidaturas
```

**Comment by camilog** [comment]
Me gusta la idea de que esté en el padrón mismo el grupo al cual pertenece una persona.
Además, el nombre que aparece en el padrón debe ser el nombre del grupo que aparece en la misma interfaz. Quedaría algo así:
```
camilo,Camilo Gómez,1,Candidaturas Oficiales
ahevia,Alejandro Hevia,1,Candidaturas Oficiales
fmacias,Fernanda Macías,1,Otras Candidaturas
rdelafuente,Raul de la Fuente,1,Otras Candidaturas
```

**Comment by JaramilloCris** [comment]
Nonono, me refiero al archivo de alternativas, acuerdate que las alternativas son los votos (candidatos) que se muestran en el dropdown, esos son los que hay que separar por grupos no?

**Comment by JaramilloCris** [comment]
Ya mi plan de desarrollo para este issue es el siguiente
- Agregar un campo a la elección mixnet que sea agrupar candidatos (un input select)
- Con este campo separar entre no agrupar y agrupar
- Para agrupar se toma el segundo valor (después de la coma)

Ej: Si tenemos el archivo de votos
`Jaume Vidal, Candidaturas Oficiales`
`Alipio Vargas, Otras Candidaturas`
`Sonia Soler,Otras Candidaturas`

Existirían dos grupos. Es necesario que cada voto tenga un grupo para esta opción
