### ISSUE TITLE
Mejoras a la interfaz (detalles)

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#4]
- [x] 1. En votación normal, las opciones Voto Nulo y Voto Blanco no se encierran en un cuadrado
- [x] 2. En votación normal, opción múltiple, no están alineadas las alternativas
- [x] 3. En votación normal, opción múltiple, dejar las opciones Voto Nulo y Voto Blanco con checkbox, al igual que el resto
- [x] 4. En la pantalla final de la cabina de votación, abrir en una nueva pestaña ambas acciones (ver certificado y ver urna electrónica)
- [x] 5. En urna electrónica, cambiar "Ver Voto" por "Ver Voto Encriptado"
- [x] #8
- [x] 7. En la pantalla final de la cabina de votación, el botón "Salir" está subrayado innecesariamente
- [x] 8. En votación normal, opción múltiple, espaciar un poco más las opciones, ya que al marcar dos que están juntas, los cuadrados quedan demasiado juntos
- [x] 9. En votación normal, opción múltiple, habilitar la opción de desmarcar Voto Nulo y Voto Blanco (sé que se desmarcan automáticamente al apretar otra opción, pero tal vez sea buena idea poder desmarcarlo directamente)
- [x] 10. En votación mixnet, las opciones Voto Nulo y Voto Blanco no se encierran en un cuadrado
- [x] 11. En votación mixnet, al apretar Voto Nulo, mejor saquemos esos caracteres para completar las opciones, yo lo dejaría tal como pasa en Voto Blanco, es decir, dejarlos sin marcar.
- [x] 12. En votación mixnet, habilitar un dropdown solo si el dropdown anterior fue marcado. Creo que podría confundir que se pueda marcar la opción 3, sin haber marcado las opciones 1 y 2
- [x] 13. Me gustaría probar como se ve la cabina de votación si es que no cambiamos el fondo, si dejamos para los 3 pasos el mismo fondo con las cajitas de colores
- [x] 14. En cabina de votación, el popup inicial con la descripción de la elección debería tener como título el nombre largo de la elección, y no el nombre corto
- [x] 15. En cabina de votación, si la pregunta tiene una descripción (escrita al momento de configurarla), hay que mostrarla en la cabina. Creo que queda bien que aparezca debajo de "(seleccionar solo 1 opción)"

**Comment by JaramilloCris** [comment]
- No entiendo el punto 6, actualmente no se muestran los botones si no hay pagina anterior o siguiente 🤔 
- El punto 11 fue algo que llegamos de acuerdo con el profe, que a el le hacia más sentido eso, le preguntaste o los saco directo nomas?
- El punto 12 también fue algo que se llego a un acuerdo en una reunión, quizás habría que conversarlo más en profundidad, en general era porque una persona podría pensar que solo tiene que hacer una selección si le aparece solo un dropdown

**Comment by camilog** [comment]
- Punto 6. Puede que lo que haya visto esté desactualizado, lo voy a revisar nuevamente. Voy a adjuntar captura de pantalla si fuere necesario.
- Punto 11. Lo conversaré con el profe entonces, creo que no me convence tanto ahora que lo vi implementado.
- Punto 12. Sí, recuerdo que lo conversamos, pero mi idea ahora no es que no aparezcan para abajo, sino que estén deshabilitados (visibles, pero que no sea posible desplegar el dropdown) y que se vayan habilitando a medida que se vayan marcando
