### ISSUE TITLE
Bug buscador de elecciones

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#43]
REPRO
- Ingresar a http://localhost:3000/psifos/admin/home
- Crear una elección con nombre corto “Elección de mascotas”
-  Crear una elección con nombre corto “eleccion-comidas”
-  Escribir en el buscador “eleccion”

ESPERADO
- La búsqueda debería entregar las dos elecciones creadas

BUG
- No aparecen resultados en la búsqueda

**Comment by camilog** [comment]
@JaramilloCris podrías revisto esto también, por favor
