### ISSUE TITLE
Cerrar sesión ante inactividad

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#48]
REPRO
- Logearse e ingresar a http://localhost:3000/psifos/admin/home#collapsible-card 
- Dejar la pestaña inactiva por 10 minutos

ESPERADO
- Después de cierto tiempo de inactividad la sesión se cierra

BUG
- La sesión sigue abierta, independientemente del tiempo de inactividad.

**Comment by camilog** [comment]
@JaramilloCris Puedes revisar esto también, por favor.
Encontré esto como un buen código para detectar inactividad: https://gist.github.com/gerard-kanters/2ce9daa5c23d8abe36c2
