### ISSUE TITLE
Limitar número de alternativas a marcar

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#5]
En votación normal, opción múltiple, hay que limitar el número de opciones que se pueden marcar. Entiendo que actualmente tira un warning si se marcaron más opciones de las permitidas, pero confunde un poco esa acción.
Así que mejor lo dejamos tal cual está actualmente en el sistema Helios-UChile.

**Comment by JaramilloCris** [comment]
En mi opinion creo que las dos opciones en conjunto son necesarias. Porque cuando se necesita una alternativa no se bloqueara pero es necesario que el usuario ingrese alguna respuesta
