### ISSUE TITLE
Bug voto nulo

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#54]
Se creó una elección con las siguientes características:

- Pregunta 1: 3 opciones, los votantes deben marcar mínimo 1 y máximo 3
- Pregunta 2: 3 opciones, los votantes deben marcar mínimo 1 y máximo 3
- Pregunta 3: 4 opciones, los votantes deben marcar mínimo 2 y máximo 3

**REPRO**

- Ingresar a la votación
- Responder a la primera y segunda pregunta
- Votar nulo en la tercera
- Apretar FINALIZAR
- Apretar ENVIAR VOTO

**ESPERADO**

- Se finaliza la elección

**BUG**

- Aun después de 5 minutos sigue cargando la validación del voto
![Captura de Pantalla 2023-05-26 a la(s) 20 44 33](https://github.com/clcert/psifos-frontend/assets/53621395/a7fac364-af04-4c30-adb6-d9986df44be5)

**Comment by JaramilloCris** [comment]
Al intentar replicar me aparece esto, sera lo que mencionaste que derivo de otra cosa? @fermacias 
![imagen](https://github.com/clcert/psifos-frontend/assets/32551270/37dc7884-aafa-45cf-a4ac-c745f246e2ec)

**Comment by camilog** [comment]
Esto está relacionado con #66 
Básicamente es incompatible (matemáticamente) tener Voto Nulo (o Blanco) y una pregunta con mínimo de 2
