### ISSUE TITLE
Opción INICIO en menú superior

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#55]
# Issue
Al visualizar la primera pregunta, el botón de INICIO en el menú superior no hace nada. 
En el panel del administrador este botón lleva al listado de votaciones, pero un votante no debería tener acceso a este espacio.
Desde la perspectiva del votante, al hablar de un inicio probablemente estaríamos hablando de https://participauchile.cl/, pero uno llega a ese mismo lugar seleccionando el logo de Participa UChile.

<img width="1439" alt="Captura de Pantalla 2023-05-26 a la(s) 16 25 26" src="https://github.com/clcert/psifos-frontend/assets/53621395/529354e7-d026-4617-966e-7c218e6741cf">

# Propuesta
Se propone que dentro de la cabina de votación, el menú superior NO tenga la opción inicio.

**Comment by JaramilloCris** [comment]
Que opinas de esto @camilog ? dejamos sin un inicio el menu del votante? o que rediriga a participa o quizas que reinicie la votación?

**Comment by camilog** [comment]
@JaramilloCris Creo que es mejor que NO haya botón INICIO. Si la persona quiere ir "para atrás", pero dentro de la cabina, debiera seguir el flujo que le presentamos (ir a las preguntas anteriores o revisar su votación). Y si quiere salir e ir al Home, tiene que apretar el logo de Participa UChile.
