### ISSUE TITLE
Simplificar flujo de custodio

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#6]
Debemos hacer que la vista de la página privada de Custodio de Clave sea más directa para el usuario, es decir, que solo tenga la opción de hacer una sola acción, dependiendo del estado de la elección.
Se identifican 3 estados: (1) antes de generar las claves, (2) después de generar las claves, y (3) esperando envío de desencriptación parcial.

- [ ] En Estado 1, debe aparecer solamente 1 botón que diga "Iniciar Generación de Claves". Luego, durante el proceso de generación, deberíamos separarlo en dos pasos: (1) Descarga de clave privada, y (2) Sincronización con otros custodios. Al finalizar el proceso de generación, un solo botón que diga "Verifica tu Clave Privada" (ingresar al Estado 2).
- [ ] En Estado 2, debe aparecer solamente 1 botón que diga "Verifica tu Clave Privada". Luego, debiera haber un espacio donde el usuario pueda subir su archivo, o bien, arrastrar el archivo al explorador. El output debe ser "Clave Verificada Exitosamente" (o un mensaje de error). Al finalizar la verificación, debe aparecer un solo botón que diga "Salir".
- [ ] En Estado 3, debe aparecer solamente 1 botón que diga "Envía tu Desencriptación Parcial". Luego, la misma ventana del Estado 2, donde se puede subir la clave privada o arrastrar el archivo. Luego, una animación que muestre que se están haciendo cosas (tal como la ventana modal de "Encriptando tu Voto"). Al finalizar, un mensaje que diga "Desencriptación Parcial enviada Exitosamente) y un botón más que diga "Salir".

**Comment by JaramilloCris** [comment]
En general con el Estado 3 no estoy muy de acuerdo, siento que cuando uno envía su desencriptación parcial debería poder antes poder verificar su clave. Cuando era custodio y eran varias elecciones en la misma ceremonia, echaba muy en falta el poder verificar la clave antes de enviarla para así no equivocarme, es un tema de igual para que el proceso en vivo no sea demoroso y no falle 🙃, porque si me equivoco puedo ir cambiando, lo que hace que me demore más

**Comment by camilog** [comment]
Tienes razón. Entonces dejemos que en Estado 3 aparezca como botón principal el "Envía tu Desencriptación Parcial", y un botón secundario (más chico, abajo) se mantenga el "Verifica tu Clave Privada".
