### ISSUE TITLE
Botón para descargar certificado no funciona

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#60]
Se creó una elección con las siguientes características:
- Pregunta 1: 3 opciones, los votantes deben marcar mínimo 1 y máximo 3
- Pregunta 2: 3 opciones, los votantes deben marcar mínimo 1 y máximo 3
- Pregunta 3: 4 opciones, los votantes deben marcar mínimo 2 y máximo 3

**REPRO**
- Responder la elección
- Enviar voto
- Apretar botón DESCARGAR CERTIFICADO DE VOTO

**ESPERADO**
- Obtener documento

**BUG**
- No pasa nada

**Comment by JaramilloCris** [comment]
@fermacias No he podido simular este bug, tienes pulleado el backend info a full? literal hice lo mismo que mencionas arriba

**Comment by camilog** [comment]
@fermacias lo que puede estar sucediendo es que se demora un poco en descargarlo. Tal vez sea bueno incluir algún "Generando Certificado..."
