### ISSUE TITLE
Pasos de una votación

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#61]
# Issue
Actualmente son 3 pasos, donde el tercero es el de envío. Sin embargo, el envío del voto se realiza realmente al finalizar el paso 2. Es decir, no hay nada que el usuario deba hacer obligatoriamente durante el paso 3.

<img width="1189" alt="Captura de Pantalla 2023-05-29 a la(s) 11 13 44" src="https://github.com/clcert/psifos-frontend/assets/53621395/85d37336-330e-496e-a14e-676739f036b1">

# Estrategia

Se decide eliminar el paso 3 y que al finalizar el segundo paso, se envíe a una nueva url donde se muestre el contenido del paso 3.

# Observación

El contenido del paso 3 de la cabina de votación fue modificado en el siguiente [PR](https://github.com/clcert/psifos-frontend/pull/64).

**Comment by JaramilloCris** [comment]
@camilog @fermacias por que se decide poner en una nueva url? no veo la necesidad pues es al finalizar el proceso de votación y el usuario no debería poner volver a acceder al paso 3 (si reingresa a la cabina vuelve al paso 1). En mi opinion siento que debería quedar en una, podemos conversarlo en la reunion

**Comment by camilog** [comment]
@JaramilloCris Lo de la nueva URL se le ocurrió a @fermacias al responder lo siguiente: ¿que debiera pasar si el usuario aprieta F5 en la pantalla de voto enviado? Entonces, si queremos que se mantenga en la misma pantalla, necesitamos que tenga una URL distinta. Lo que sucede ahora es que al ser la misma URL, se reinicia el proceso de votación, que no tengo claro si es el comportamiento que esperamos

**Comment by JaramilloCris** [comment]
Hablemoslo en la reu porque para el flujo que tenemos siento que no tiene mucho sentido, porque si recarga le mostramos el ultimo voto emitido?
