### ISSUE TITLE
Reload durante votación

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#62]
**REPRO**

- Iniciar el proceso de votación
- Responder la primera pregunta
- Hacer reload

**ESPERADO**
- Mostrar mensaje de confirmación que indique que si se hace reload se perderá el progreso que se lleva hasta el momento

**BUG**
- Se reinicia el proceso de votación

**Comment by JaramilloCris** [comment]
A que te refieres con hacer reload? A hacer un f5? @fermacias

**Comment by camilog** [comment]
@JaramilloCris Sí, es actualizar la página. Tal vez podemos capturar todos esos eventos que harían sacar a la persona de la página (actualizar, irse al home, cerrar pestaña/ventana) y lanzarle un mensaje que si lo hace se va a perder su avance. De aceptar, lo otro que deberíamos hacer sería desloguear a la persona (de la misma manera que eventualmente lo haremos en #56), y luego realizar la acción que quería hacer el votante

**Comment by camilog** [comment]
@JaramilloCris Ojo que al querer salir en la última página, manda el aviso también.
Deberíamos sacarlo si es que estoy al final (en la pantalla de Envío)

**Comment by camilog** [comment]
Solucionado por dbba396
