### ISSUE TITLE
Colores en barra de progreso

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#63]
A medida que se van completando etapas de una votación los colores de los enunciados deben ir variando, con la finalidad de mostrar:
- Las etapas que ya pasaron
- La etapa en la que me encuentro
- Las etapas que aun no comienzo

<img width="1196" alt="Captura de Pantalla 2023-05-29 a la(s) 11 19 15" src="https://github.com/clcert/psifos-frontend/assets/53621395/c1843fe0-d12d-4217-9a74-f863f10395ab">

** Las imágenes que permiten realizar esto ya existen, solo falta aplicarlas
- https://github.com/clcert/psifos-frontend/pull/103

**Comment by camilog** [comment]
![image](https://github.com/clcert/psifos-frontend/assets/4451287/62e1ae6c-a1d0-42aa-97e2-533e2c64b609)
![image](https://github.com/clcert/psifos-frontend/assets/4451287/3589d50c-d295-4b8c-a9b8-b4b7fdb1f649)
![image](https://github.com/clcert/psifos-frontend/assets/4451287/ab1afe73-c70f-4ccb-93af-fc1729db9974)
@fermacias

**Comment by fermacias** [comment]
@camilog como era la simbología de colores? Recuerdo que era algo como lo siguiente
- Azul: Paso futuro
- Celeste: Paso actual
- Gris: Paso finalizado (?)
- Verde: Paso finalizado (?)

**Comment by camilog** [comment]
A priori es:
Gris: paso futuro
Azul/Celeste: paso actual (hay que elegir cual se ve mejor)
Verde: paso finalizado 

La idea es seguir algún guideline de colores para horizontal stepper
