### ISSUE TITLE
Ordenar ponderación

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#72]
En la pantalla de Estadísticas en Portal de Información, los ponderadores deberían mostrarse en orden creciente: 0.125 - 0.5 - 1

![imagen](https://github.com/clcert/psifos-frontend/assets/4451287/f41ce3e1-6cc7-4177-bdfd-4ce7c54defc2)

**Comment by JaramilloCris** [comment]
@camilog Esto quedo listo
