### ISSUE TITLE
[Portal de información] Enumeración en urna electrónica

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#73]
<img width="1213" alt="Captura de Pantalla 2023-06-26 a la(s) 18 10 32" src="https://github.com/clcert/psifos-frontend/assets/53621395/33e220dd-359d-4238-9d78-d443f51cc3b8">

La enumeración indica _Página 1 de 1 (Mostrando 1-50 de 30 resultados)_, debería indicar  _Página 1 de 1 (Mostrando 1-30 de 30 resultados)_.

**Comment by JaramilloCris** [comment]
Creo que ese 50 lo habíamos dejado por el tamaño máximo, @camilog que opinas?

**Comment by camilog** [comment]
@JaramilloCris Estoy de acuerdo con @fermacias, ya que el ejemplo tiene menos de 50 entradas, entonces debería decir _1-30_
Cuando haya más de 50 votos, entonces debería decir _Página 1 de 1 (Mostrando 1-50 de 75 resultados)_
