### ISSUE TITLE
[Portal de información] Resultados

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#75]
# Porcentajes
No queda claro cual es el total sobre el que se calculan los porcentajes.
Por ejemplo, en los resultados de la siguiente [elección](https://participa.uchile.cl/psifos/booth/eleccion-med-kine-2023/public-info), el candidato Cano obtuvo 8 votos. Si se calcula el porcentaje sobre los votos recibidos resulta 21.05%, mientras que al calcularlo sobre el total del padrón resulta 17.7%.
<img width="1268" alt="Captura de Pantalla 2023-06-26 a la(s) 19 13 41" src="https://github.com/clcert/psifos-frontend/assets/53621395/06f5cabd-6682-4a13-a4ae-6588e08c3d24">

# Votantes por ponderación
Cuando hay variedad de votantes se debiera ver así
<img width="1348" alt="Captura de Pantalla 2023-07-05 a la(s) 17 57 46" src="https://github.com/clcert/psifos-frontend/assets/53621395/b290a92c-7387-47e4-aa74-c83bb362f9ea">

Cuando no la hay (`max_weight == 1`) no debería aparecer, pero actualmente aparece así:
![image](https://github.com/clcert/psifos-frontend/assets/53621395/de493a74-6639-49cf-aacb-07ee23c7e19a)

# Solución
- https://github.com/clcert/psifos-frontend/pull/86
- https://github.com/clcert/psifos-frontend/pull/79

**Comment by camilog** [comment]
Listo :+1:
