### ISSUE TITLE
[Portal de información] Mejoras de interfáz

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#76]
# Estadísticas
<img width="996" alt="Captura de Pantalla 2023-06-26 a la(s) 19 29 33" src="https://github.com/clcert/psifos-frontend/assets/53621395/a56597ce-a50f-4ee6-bf31-12d6ff8eba1e">
El cuadrado inferior izquierdo se ve como si la intención fuera _Votos ponderación: 0.5 (6 votos)_, cuando en realidad la intención es _Votos ponderación 0.5: 6 votos_.
Esto se puede arreglar manejando el estilo de la letra, por ejemplo, poniendo en cursiva el título.

# Resumen
<img width="1252" alt="Captura de Pantalla 2023-06-26 a la(s) 19 34 01" src="https://github.com/clcert/psifos-frontend/assets/53621395/9724fa9a-1e83-40b6-92a4-d6c4db588b92">
En las tablas, las cifras solas (sin porcentaje) deben estar alineados a la derecha.
El usuario debe tener la posibilidad de considerar o no los votos nulos y blancos en la visualización de las estadísticas (porcentajes).

# Solución
- https://github.com/clcert/psifos-frontend/pull/89

**Comment by camilog** [comment]
Fixed :+1:
