### ISSUE TITLE
Mejorar urna electrónica

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#8]
- [x] Desactivar botón "Siguiente" si no existe otra página en la urna
- [x] Agregar información de página actual y número de registros que se muestran, junto con el número de registros totales. Ej: Página 1 de X (Mostrando 1-50 de 1000 resultados)

**Comment by JaramilloCris** [comment]
Este punto lo pushie directamente dado que no solo se tiene que hacer cambios en el front, también en el back informativo. Esta subido, haz pull a los dos repositorios y pruebalo :cat2:

**Comment by camilog** [comment]
![issue_urna](https://user-images.githubusercontent.com/4451287/227945191-6844d7b2-4895-4f6d-a152-517e816b97bb.gif)

Hay un elemento por página, cuando debiera haber 50 elementos por defecto

**Comment by JaramilloCris** [comment]
Esta issue esta lista?

**Comment by camilog** [comment]
Podríamos incluir aquí el hecho de mostrar solamente los votos que han llegado, y no desplegar los "espacios vacíos"

**Comment by JaramilloCris** [comment]
Oka, me pongo a ello

**Comment by JaramilloCris** [comment]
Modifique la consutlta del backend informativo para que envié solo votos validos. Pullea y pruebalo @camilog

**Comment by camilog** [comment]
Perfecto! Con eso se concluye este issue
