### ISSUE TITLE
[Urna electrónica] Botones responsive

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#82]
# Issue
Al finalizar el proceso de votación aparecen los siguientes mensajes. 
![image](https://github.com/clcert/psifos-frontend/assets/53621395/6d54c8d2-8dd7-4861-a71e-a2edbfa506f4)
Los botones deben ser responsivos.

# Antecedentes
Al jugar con el navegador falla con la vista de Galaxy fold

# Solución
#85

**Comment by camilog** [comment]
Listo :+1:
