### ISSUE TITLE
[Portal de información] Tablas de resultados deben ser seleccionables

### ISSUE THREAD

**Issue by fermacias** [clcert/psifos-frontend#83]
# Issue
Al ingresar a la sección de resultados, los candidatos dentro de las tablas deben ser seleccionables, al igual que los otros elementos.
Link de referencia: https://participa.uchile.cl/psifos/booth/eleccion-med-kine-2da-2023/public-info
Imagen de referencia:
![image](https://github.com/clcert/psifos-frontend/assets/53621395/f452af9c-25c4-42d9-8f54-9d18665fdb3e)

# Resuelve
#84

**Comment by camilog** [comment]
Listo :+1:
