### ISSUE TITLE
Cambiar UUID por short_name en URL

### ISSUE THREAD

**Issue by camilog** [clcert/psifos-frontend#9]
Creo que es mejor que en las distintas URLs aparezca el short_name de la elección, en reemplazo de la UUID. Lo hace más entendible para el votante y mejor estéticamente.

**Comment by JaramilloCris** [comment]
Listo, esto quedo arriba (me motive y lo refactorice todo jaja) probe funcionalidades básicas (una elección hasta obtener los resultados) y todo anduvo bien, te pediría que cualquier cosa que no funcione me la hagas saber, al cambiar el election uuid por el short name en todas las funcionalidades pueden pasar cosas jeje.

- Hay que pullear los dos backend y el front
